accounts:
  - name: alice
    coins: ["20000token", "500000000stake"]
  - name: bob
    coins: ["20000token", "200000000stake"]
  - name: xavier
    coins: ["20000token", "300000000stake"]
    address: cosmos1z3978xhvm0yrctl2hf9jhrnktzzz5x690sh0qa
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
